version: 1
rag_sources:
  - path: "docs/adr/**/*.md"
    weight: 0.9
  - path: "docs/guides/**/*.md"
    weight: 0.3
  - path: "README.md"
    weight: 0.2
rules:
  - name: "Block TODOs"
    condition: "banned-terms"
    terms: ["FIXME"]
    severity: "error"
  - name: "AI Database Policy Check"
    condition: "ai-review"
    severity: "error"
    prompt: "Analyze the code changes. If any code attempts to use or connect to a MongoDB database, you MUST report it as a policy violation. Reference the ADR documentation in your reasoning."