version: 1
rules:
  - name: ai-style-guideline
    condition: ai-review
    severity: error
    tags: ['style','ai-review']
    prompt: |
      Run a style pass on the changed files and report inconsistencies with common JS/TS conventions:
      missing returns, inconsistent naming, long lines >120 chars, and poor variable names. Provide short suggested edits.