version: 1
rules:
  - name: ai-dependency-risk
    condition: ai-review
    severity: error
    tags: ['dependency','ai-review']
    prompt: |
      Inspect package usage in code diffs for references to new or risky third-party libraries.
      For each new dependency found, evaluate whether it's mature, widely used, or likely risky (unmaintained,
      small download counts). If risky, recommend alternatives or require an ADR justification.