version: 1
rules:
  - name: "Block TODOs"
    condition: "banned-terms"
    terms: ["TODO", "FIXME"]
    severity: "error"
  - name: "Require Changelog"
    condition: "require-changelog"
    severity: "error"
  - name: ai-performance-hotpath
    condition: ai-review
    severity: error
    tags: ['performance','ai-review']
    prompt: |
      Detect potential performance issues: synchronous blocking operations in async code, O(n^2) loops on arrays,
      heavy string concatenation in loops, or repeated DB calls inside loops. Suggest batched or memoized approaches.