version: 1
rules:
  - name: "No console in src"
    condition: "no-console-in-src"
    enabled: true
    allowedMethods: ["console.warn"]
    severity: "error"
    message: "Disallowed console usage detected. Use proper logging instead."
    paths:
      - "src/**"
    errorCode: "CONSOLE_NOT_ALLOWED"
    tags: ["lint", "console"]
  - name: "Block TODOs"
    condition: "banned-terms"
    terms: ["TODO", "FIXME"]
    severity: "error"