version: 1
rules:
  - name: ai-complexity-check
    condition: ai-review
    severity: error
    tags: ['security','ai-review']
    prompt: |
      Identify functions with apparent high cyclomatic complexity or deeply nested loops/conditionals.
      Recommend refactors (extract functions, early returns, small helper utilities). If a function looks complex,
      return which function and line ranges and a suggested refactor summary.